s=set()# is called empty set empty set hamesha aise banta hai na ki s=[]sahi tarika hai-> s = set ()
n= input("Enter a number:")
s.add(int(n))
n= input("Enter a number:")
s.add(int(n))
n= input("Enter a number:")
s.add(int(n))
n= input("Enter a number:")
s.add(int(n))
n= input("Enter a number:")
s.add(int(n))
print(s)